name: CDK-state-machine Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.GH_AWS_IAM_ROLE }}
        aws-region: us-east-1

    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Install CDK
      run: npm install -g aws-cdk

    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: 'CdkStateMachineStack'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
